name: project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-lastest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
